base_url = "https://amuseee.github.io"
title = "~vrajesh"
description = "my corner of the internet"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["static/highlight_themes"]
highlight_themes_css = [
    { theme = "Amigadark", filename = "hl-light.css"},
    { theme = "Amigalight", filename = "hl-dark.css"},
]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

name = "Vikshar Rajesh"
id = "amuseee"
bio = "aegroto, dum anima est, spes est"
avatar = "https://live.staticflickr.com/23/26434229_aea5a38ab8_z.jpg"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/amuseee" },
    { name= "Email", icon = "email", url= "mailto:viksharrajesh@gmail.com" },
]

homepage_layout = "about"

recent_max = 5
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "projects", path = "/projects", is_external = false },
    { name = "blog", path = "/blog", is_external = false },
    { name = "resume", path = "", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true
blog_categorized = false
blur_effect = true

toc = true
comment = false
copy = true
back_to_top = true

outdate_alert = false

footer_credits = true
footer_copyright = "vik, 2024"

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
